### ISSUE TITLE
[FEAT] <wps now has the latest version >

### ISSUE THREAD

**Issue by gzxiexl** [linuxserver/docker-wps-office#2]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

wps now has the latest version 11.1.0.11704
https://www.wps.com/whatsnew/linux/

I installed docker-wps-office in docker-kasm (with internationalization mods set up), but the interface is still in English. I noticed that the download links provided by wps.cn and wps.com are different.

https://wps-linux-personal.wpscdn.cn/wps/download/ep/Linux2019/11704/wps-office_11.1.0.11704_amd64.deb
https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/11704/wps-office_11.1.0.11704.XA_amd64.deb

### Reason for change

Improving the experience of Chinese users

**Comment by thelamer** [comment]
Please pull the latest image and run it with the following environment variables: 
```
-e DOCKER_MODS=linuxserver/mods:universal-internationalization \
-e LC_ALL=zh_CN
```

**Comment by thelamer** [comment]
@gzxiexl I added a Chinese tag
linuxserver/wps-office:chinese

Can you test it out when you get a chance?

To enter simplified Chinese you will have to enable IME input mode in the sidebar settings.

**Comment by homerr** [comment]
Update if issues return
