### ISSUE TITLE
[FEAT] <title>WPS has a new version

### ISSUE THREAD

**Issue by nine-city** [linuxserver/docker-wps-office#6]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please update the WPS version in the image

### Reason for change

The new version number of WPS is 12.1.0.17885
For detailed information, please refer to the official website
https://www.wps.com/office/linux/

### Proposed code change

No

**Comment by nine-city** [comment]
Hello, the Linux version of the WPS Chinese official website has been updated. Please update the WPS version in Docker
The current version is 12.1.0.17900
https://linux.wps.cn

**Comment by aptalca** [comment]
Versions are retrieved and built automatically from arch's aur repo: https://github.com/linuxserver/docker-wps-office/blob/master/Dockerfile#L28

You don't need to ping us every time there is a new version.

**Comment by nine-city** [comment]
so sorry...emmm
As far as I know, the WPS version of Arch's aur repo is far behind the official version
Once again, thanks

**Comment by aptalca** [comment]
Sorry, linked the wrong branch
Here's the actual one: https://github.com/linuxserver/docker-wps-office/blob/chinese/Dockerfile#L30

It's arch based and our arch based images update every Friday (because arch is rolling, we have to update the baseimage and the downstream images at the same time).
